apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{team}}
  labels:
    team: {{team}}
spec:
  accessPolicy:
    outbound:
      rules:
        - application: spesialist
          cluster: dev-gcp
          namespace: tbd
  image: {{image}}
  port: 3000
  ingresses:
    - https://speil.intern.dev.nav.no
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: isAlive
    periodSeconds: 5
    timeout: 1
  readiness:
    initialDelay: 20
    path: isReady
    timeout: 1
  redis:
    - instance: sessions
      access: readwrite
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      cpu: "2000m"
      memory: "512Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
  prometheus:
    enabled: true
  frontend:
    generatedConfig:
      mountPath: /app/dist/client/nais/nais
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "611669fa-de5c-4dc2-a0e8-6041a019992a"
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c"
          - id: "c811e9f4-26a6-43f9-b930-8c83365683a9"
          - id: "59f26eef-0a4f-4038-bf46-3a5b2f252155"
          - id: "317665ad-1402-458e-b8e6-9cb50afc1252" # speil-brukere-dev
  secureLogs:
    enabled: true
  envFrom:
    - secret: speil
  env:
    - name: DEBUG
      value: global-tunnel
    - name: CLIENT_ID_SPESIALIST
      value: api://dev-gcp.tbd.spesialist/.default
    - name: LOGOUT_URL
      value: https://speil.intern.dev.nav.no
    - name: SPESIALIST_BASE_URL
      value: http://spesialist
    - name: SPESIALIST_WS_URL
      value: ws://spesialist
